### ISSUE TITLE
Canceling Demos

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/trainers#105]
A trainer asked about canceling a demo that no one had signed up for and on what time scale this should happen.  Some sort of plan or how to answer this should be added to the trainer guide maybe?

**Comment by ragamouf** [comment]
Thanks @brownsarahm! That was me. I cancelled the teaching demo 2 weeks out because noone had signed up, and there were spaces in my timezone either side in other teaching demos. I think this is a good rule of thumb because this would normally be the time that I would ensure the teaching demo is in the instructor trainees calendars and confirm their chosen lessons.

**Comment by karenword** [comment]
People should always be able to remove an empty slot that no longer works for them, whatever the lead time. For cancellations *due to* no enrollment, 1-2 weeks seems fine to me. 

We should probably document cancellation procedures as well as guidelines somewhere other than the emails that go out about these things, too.

**Comment by karenword** [comment]
Sorry I'm doing confusing things here -- I'm not sure how assignments should work in this repo but tagging @maneesha fyi.

**Comment by brownsarahm** [comment]
Yeah i think the key is to separate when to cancel vs find someone else to cover and how/where to notify.  (and what places need to get updated to reflect the change)

**Comment by brownsarahm** [comment]
I think this is resovled with the [updates to the guide](https://github.com/carpentries/docs.carpentries.org/commit/b53102f75326c48c001b5b3f86dc99c7b370fa57) to add a [canceling a demo section](https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#canceling-a-demo)
