### ISSUE TITLE
Feedback on Instructor Training Attendance Requirements

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/trainers#123]
Relaying here some feedback given by a community member, whose colleague recently attended an online Instructor Training workshop:

>My team mate reported to me that some aspects of the training appeared contradictory to the core values of the carpentries (as I perceive them). As an example, this statement was circulated prior to the training:
> 
> > _Attendance is required for the full workshop in order to certify as a Carpentries Instructor. Participants who miss more than one hour will not pass our training requirements._
> 
> My colleague had family duties and hence couldn’t attend the full instructor training as [they] needed to tend to [their] kids. [They were] able to organize someone to take over but found this statement not very inclusive (which is something that the carpentries stand for above any other community I know).

Sharing here in case the Trainer Leadership wishes to discuss whether the attendance requirements for certification should be relaxed, or if this wording should be adjusted, for virtual Training events held under Covid restrictions.

**Comment by brownsarahm** [comment]
Thanks @tobyhodges this raises multiple interesting points. 

@karenword @klbarnes20  in practice if a trainer reports that a trainee misses more than an hour, what actually happens? My understanding was that what's happening in practice is more flexible than this suggests, so maybe we should update the language. 

This also relates to #78 and where policy statements exist and who owns them. Since this comes from the template that lives in the handbook, the Core team currently owns it, but as policy that relates to the curriculum maybe it is within the leadership's powers?  

My personal opinion is that we should put in place, and communicate a clear accommodation, but not relax the spirit of this policy. I think the whole curriculum really is important for trainees to work through, but that we could have some sort of makeup.

**Comment by karenword** [comment]
@talishask may be able to provide more detail, but on the admin side, if people are marked absent for a section of the training event, they are generally marked absent in our database and may be asked to repeat if they wish to be certified. If we are specifically contacted by Trainers or Trainees about options for people who had to miss a segment of the training, these are referred to me, and I have been setting up one-on-one makeup sessions. 

Neither of these is particularly satisfactory. The former is unforgiving and the latter is unscalable. And relying on people to ask is inequitable.

This is in a grey area between Core Team and Trainers Leadership -- it is one part admin and one part checkout requirements. I think the key questions for Leadership are: 
- how firm do we want to be about attendance in regards to checkout eligibility? 
- What should count as a make-up option, and 
- should the Trainer community have a role in providing makeup opportunities? 
Whereas Core Team would be left with decisions about when and how people can or should re-take training, and the role Core Team can play in continuing to provide makeup options.

These may be longer term questions as Leadership finds its feet on how to address these sorts of things. In the short term, it is likely that softening the language a bit to encourage people to inquire about makeup opportunities will not create overwhelming demand.

**Comment by psteinb** [comment]
I'd love to add my thoughts on this. Full disclosure: I was the community member, the respected @tobyhodges gave a voice to and created this issue for. :pray: 

I think it is vital here to stay practical and dynamic. The Carpentries are an international, inclusive and open community. For me this does not motivate bringing forward rules that some parts of the community follow by the letter and others may interpret rather vaguely. I think a balance needs to be kept and the focus should lie on the content conveyed.

I do understand that when it comes to educating new instructors, the quality level, methods and goals of the carpentries have to be handed over. And this is something very worthwhile to ensure. However, being too strict about the subsequent check-out process appears impractical to me ... and can mean to exclude learners (as it happened here due to child care obligations). We have most (if not all) material available on websites and repos. Therefor, restrictions like:

> Participants who miss more than one hour will not pass our training requirements.

Make no sense at all. It should be clear to learners, that if they miss parts of the course, they simply miss a chance to learn and practice. And to my mind, it should be their obligation to make up for this. See comment by @brownsarahm :wave: . 

During the check-out process, there is even more to learn. And this leads me to one of the key values of the carpentries IMHO: formative assessment in favor of summative assessment. We should take this concept to our hearts and also structure the instructor training plus check-out in such a fashion, i.e. 

**less** strict rules and a grading style environment, e.g. "if you don't do/pass A, you will fail to B"
**more** here is a rough plan including a goal, we installed the process to help the candidate instructor to learn (rather than being graded). 

To conclude and reply to @karenword : I wonder, what would be a formative assessment at the end of each lesson/module/day of the instructor training so that learners can check where they are (i.e. also serves as make up)? This assessment to my mind should be part of the lesson itself. So no need to consider responsibilities of teams for too long that create+decide on operative rules. Let's create an issue and install these assessments in due course inside the material. Then the question of makeup lies in the responsibility of the instructor training coaches (potentially including one external instructor). This scales and abides to the values of the carpentries.

**Comment by ACharbonneau** [comment]
Due to lack of interest/participation we're closing this for now.
