### ISSUE TITLE
A-la-carte Instructor Training Discussion

### ISSUE THREAD

**Issue by kariljordan** [carpentries/trainers#37]
The purpose of this issue is to gather feedback from Carpentries Trainers and the Carpentries Instructor Training Team about a-la-carte instructor training. We generally approve all a-la-carte events that Trainers request, but we reserve the right to review them. Several events were not approved recently as we do not have the capacity to meet our current training needs (through Membership). The concern we are hearing is that Trainers would like to volunteer their own time to run events in communities we are not currently reaching. Several of these training events were not approved by the Instructor Training Team.

@karenword has been discussing recognition of effort and its equivalency in the economy of The Carpentries. In her words:

> For some of our Trainers, the effort they invest in our program is formally credited to their institutions as a discount to membership. For other Trainers, there is no recognition or credit for the same effort. Furthermore, when Trainers invest additional time -- running extra demos or training events, curriculum maintenance or leadership -- there is no acknowledgement of this above-and-beyond investment. This feels unfair to some. It *is* unfair. At this time, the decision to suspend a-la-carte events comes down to capacity. If we can not meet our member capacity, we should not commit to other events. 

Though we desire to reach diverse communities with our workshops and instructor training, our Instructor Training program is a vital component of our Membership program, which generates a significant percentage of our revenue. Until we are able to build out our Membership program and include more benefits, we recommend reducing the number of "free" instructor training events that our Trainers run.

Please share your thoughts and perspective on this issue below.

**Comment by lauracion** [comment]
Thank you for opening this discussion! 

As a trainer in a region with, afaik, no members and who doesn´t belong to a member institution, ei everything I do for The Carpentries is 100% volunteer work, there are many points in this message that I don´t follow. 

I know I am not the norm in the community. Also, The Carpentries is largely underdeveloped in Latin America. However, I am wondering if we could make this a topic of one of our trainer´s meeting so all details and nuances can be presented with a bit more detail than an issue on GitHub allows.

Thank you!

**Comment by brownsarahm** [comment]
>  I am wondering if we could make this a topic of one of our trainer's meeting so all details and nuances can be presented with a bit more detail than an issue on GitHub allows.

+1 to this

**Comment by orchid00** [comment]
Thank you @kariljordan for opening this issue. I'm sure many of us would like to talk more about this. The idea of scheduling a meeting is great 👍 +1 to @lauracion suggestion. I would suggest that before a meeting we write some examples/thoughts in a collaborative document. So we can reference to that during the meeting for details. 
I should also put upfront that I am not part of a member organisation at the moment and that everything I do for The Carpentries is 100% volunteer work. I was in 2018 part of a member organisation when I did instructor training and other carpentries training events as part of my job. But, also I put my own time outside working hours to support training, demos, translations for the community in Latin America. Of course, I wouldn't ask anyone to do extra work, but I think we should encourage those who want to embark this effort and support them as much as possible.

**Comment by MasamiYama** [comment]
Thank you for raising the issue. Currently I am working to get Japanese Carpentry community up and running. There is no member institution in Japan currently while there are a few certified instructors. To promote the Carpentries, perhaps we need to deliver actual Carpentry workshops for R / Python, so, we started translating one of R course. Translation is a tedious work (unfortunately) and people come and go. So, we need to promote the Carpentries’ benefit and attract more people -> We have to deliver workshops to demonstrate the Carpentries’ benefit -> We need more instructors to deliver workshops -> We need a member institution and run an instructor training -> To attract institution a membership, we need to demonstrate the benefit of the Carpentries -> We need to deliver workshops -> We need more people -> …  I just feel my thoughts are going circles.

**Comment by lexnederbragt** [comment]
It would help me understand this issue better if you defined 'a-la-carte events'. I think I know what you meant but I'd like to be sure we what we are talking about. Could you also maybe describe some of the ones that were, and were not approved - in general terms without revealing people/institutions involved?

**Comment by zpainter** [comment]
I'd second the question about defining what 'a-la-carte events' means. I realize that the certification process is a bottleneck for some, and in general we want to carefully expand when we can.

Also MasamiYama, we had an instructor here who moved back to Japan. He might be interested in participating with you!

**Comment by MasamiYama** [comment]
Hi Zac,

Thank you for breaking news :) I would like to be in touch with a person you mentioned! How can I do that?

> I'd second the question about defining what 'a-la-carte events' means. I realize that the certification process is a bottleneck for some, and in general we want to carefully expand when we can.
> 
> Also MasamiYama, we had an instructor here who moved back to Japan. He might be interested in participating with you!

**Comment by zpainter** [comment]
> Hi Zac,
> 
> Thank you for breaking news :) I would like to be in touch with a person you mentioned! How can I do that?
> 
> > I'd second the question about defining what 'a-la-carte events' means. I realize that the certification process is a bottleneck for some, and in general we want to carefully expand when we can.
> > Also MasamiYama, we had an instructor here who moved back to Japan. He might be interested in participating with you!

I don't have any contact information for him directly, but he does list his profile on the Carpentry website. His Github is below; he taught at a few workshops for us at Stanford.

https://github.com/megane0-0

**Comment by Denubis** [comment]
For myself -- I see how my university is struggling to pay for membership. Looking at the above, many of us are trying to build communities. It would be nice if there was some value or coupon attached to an approved ala carte event that we could give to the institution of our choice, hopefully making it easier for them to join the carpentries. (Or even, if there were established value lists that we, as trainers, could present to our institutions so that they be strategic with our time allocation)

**Comment by lexnederbragt** [comment]
Apologies for a long comment…

OK, so I think I now understand that a-la-carte workshops are. Please correct me if I am wrong... These are not part of instructor trainings listed on the calendar https://carpentries.github.io/instructor-training/training_calendar/index.html or organised especially for a member as part of their membership agreement. These trainings are then initiative of a trainer who wants to serve a certain community, for example.

If this is correct, I think the term 'a-la-carte' is confusing. To me, 'a-la-carte' would mean a content mix&match, so not a workshop following the instructor training lesson material (https://carpentries.github.io/instructor-training) but replacing things from it with other things, or using only selected lessons. I guess the workshops we discuss here could maybe be called ‘self-organised instructor training’ events?

This issue, then, has perhaps to do with motivation of folks for being a trainer. Partly this will be to help The Carpentries increase its instructor base, so more workshops can be organised and more people can learn the skills we teach. But there may also be other reasons, connected to being part of a membership organisation for example.

If I am correct here, then there could become a tension for a trainer between 
- on the one hand investing in trainings for the benefit of The Carpentries, including training people you don't know and have no relationship with; these trainings are an important part of what brings in funds to the organisation
- on the other hand wanting to run a self-organised workshop for a local audience or to help start building a trainer base in a region that does not have them, or whatever other reasons

Being told by The Carpentries such a self-organised workshop is not approved may be demotivating. I don't know the wording and implications of a non-approval, so I am basically guessing here. Perhaps these trainings don’t count towards the required number of trainings trainers agreed to run, and a self-organised, non-approved workshop then becomes an extra one you have to do ‘in your spare time’.

Sorry to not being able to add solutions to this problem, because as of now I don’t have any…

**Comment by kariljordan** [comment]
We previously discussed 50% of workshop fees from for-profit organisations being allocated for events in underserved areas, but I wanted to bring to everyone's attention that the wording on our [website](https://carpentries.org/workshops/#workshop-cost) actually reads as follows:

_**50% of workshop coordination fees for for-profit organisations go towards supporting workshops in areas with financial need.**_

What we’re supposed to do is take 50% of workshop fees from for-profit orgs (for example, if Cummins pays $10K for a workshop, we will take $5K) and use that to support workshops in areas of financial need. We would spend time centrally coordinating the event, waive the **workshop fee**, and cover travel costs for instructors.

Once Sher shares the number of for-profit workshops projected with the Business Team, we'd provide a quarterly amount for fee waivers that we can offer.

I bring this up because this language does not include instructor training, so a-la-carte events are not in that workflow. This is for informational purposes only as we continue to have this discussion.

**Comment by mkuzak** [comment]
I think this is an important discussion, thank you @kariljordan. @lexnederbragt thank you for a great summary. I like calling those "self-organised instructor training", it is much clearer. For me, involved in building local capacity in the Netherlands it is important to be able to teach those "self-organised instructor trainings". We have a few member organisation in the Netherlands but we need to be able to train people in other organisations, to attract them and with the hope, they will become member organisations in the future.

**Comment by dvanic** [comment]
I'm not sure if this is part of the trainer governance committee/question. Perhaps this is something the new committee should discuss/consider/work on?

**Comment by karenword** [comment]
This issue has largely been addressed through a variety of systemic changes, including approval of a "sponsored Instructor Training" program open to Trainers and invited applicants that has been approved by The Carpentries Executive Council as well as "a-la-carte" pricing and discounts now available through our Membership program. We will continue to look for ways to recognize the significance of volunteer effort toward our programs with related benefits. I am closing this issue, but others are welcome to create new issues directed at our current policies and programs if they feel the spirit of this issue has not been adequately resolved.
