### ISSUE TITLE
What should the criteria for Leadership service be?

### ISSUE THREAD

**Issue by karenword** [carpentries/trainers#55]
In particular, do we want to have a path for new Trainers to be involved in Leadership?

**Comment by karenword** [comment]
I'm going to go ahead and suggest that we should actually have no particular criteria here, other than Active status as a Trainer, and should let the voting community decide what criteria they wish to apply in selection.

**Comment by Denubis** [comment]
I support leaving it to the norms of the community. I do not support having a specific path for specifically new trainers to be involved.

**Comment by brownsarahm** [comment]
I agree. I'm generally in favor of a smaller leadership group that is encouraged to recruit broader participation for smaller projects so that a large number of people can be involved on an as-interested/available basis and the leadership provides the continuity, rather than doing all the work. 

We have a small panel size (5 people) that should encourage creating lots of subcommittee work as opportunities for people.

**Comment by zpainter** [comment]
I would also support no particular criteria in this instance. Part of the point of this organization is that we have multiple avenues and pathways of service, and none should be privileged over others in leadership selection.

**Comment by ragamouf** [comment]
I would support not having particular criteria for the reasons already mentioned. Also, I think the Carpentries mentoring program is something that can cater for new trainers to explore paths to leadership.
